import type { Metadata } from "next";
import { Nanum_Brush_Script } from "next/font/google";
import "./globals.css";

const fontSans = Nanum_Brush_Script({
  variable: "--font-nanum-brush-script",
  weight: "400",
  subsets: ["latin"],
});

const fontMono = Nanum_Brush_Script({
  variable: "--font-nanum-brush-script",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} ${fontMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
